"""add organization unit to users

Revision ID: 1da27fda3263
Revises: 6de1f51f404e
Create Date: 2026-08-28 00:39:11.840798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da27fda3263'
down_revision: Union[str, Sequence[str], None] = '6de1f51f404e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organization_units', ['organization_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_unit_id')
    # ### end Alembic commands ###
