"""add machine status to layouts

Revision ID: c0dd0766187b
Revises: b82461f05a97
Create Date: 2026-08-28 01:16:23.052358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dd0766187b'
down_revision: Union[str, Sequence[str], None] = 'b82461f05a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layouts', sa.Column('machine_status', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layouts', 'machine_status')
    # ### end Alembic commands ###
